#!/usr/bin/env python3
"""Render article flowcharts from Mermaid sources.

Only flowchart/architecture/state-machine figures are generated here. Data
figures are generated by generate_sciplot_data_figures.py, and frontend
screenshots are intentionally left untouched.
"""

from __future__ import annotations

import subprocess
import textwrap
import time
import base64
import json
import socket
import urllib.request
from dataclasses import dataclass
from pathlib import Path

import websocket
from PIL import Image, ImageChops


ARTICLE_DIR = Path(__file__).resolve().parent
IMAGE_DIR = ARTICLE_DIR / "images"
SOURCE_DIR = IMAGE_DIR / "mermaid_sources"
TMP_DIR = Path("/tmp/agent-firewall-mermaid-render")
CHROME = Path("/Applications/Google Chrome.app/Contents/MacOS/Google Chrome")

CLASS_DEFS = """
classDef ingress fill:#fee2e2,stroke:#dc2626,stroke-width:2px,color:#111827;
classDef proxy fill:#dcfce7,stroke:#16a34a,stroke-width:2px,color:#111827;
classDef runtime fill:#dbeafe,stroke:#2563eb,stroke-width:2px,color:#111827;
classDef llm fill:#fef3c7,stroke:#ca8a04,stroke-width:2px,color:#111827;
classDef gate fill:#ffedd5,stroke:#f97316,stroke-width:2px,color:#111827;
classDef provider fill:#ede9fe,stroke:#7c3aed,stroke-width:2px,color:#111827;
classDef audit fill:#f1f5f9,stroke:#475569,stroke-width:2px,color:#111827;
classDef block fill:#fee2e2,stroke:#dc2626,stroke-width:2px,color:#111827;
classDef allow fill:#dcfce7,stroke:#16a34a,stroke-width:2px,color:#111827;
classDef modify fill:#fef3c7,stroke:#ca8a04,stroke-width:2px,color:#111827;
classDef note fill:#ccfbf1,stroke:#0891b2,stroke-width:2px,color:#111827;
"""


@dataclass(frozen=True)
class FlowFigure:
    slug: str
    width: int
    height: int
    code: str


def chart(body: str) -> str:
    return textwrap.dedent(body).strip() + "\n\n" + CLASS_DEFS.strip() + "\n"


FIGURES = [
    FlowFigure("fig_2_1_trust_boundaries", 2100, 1200, chart("""
        flowchart LR
          A["外部消息入口<br/>Telegram / 后续入口"]:::ingress
          B["模型前控制点<br/>/agent/chat + /v1/scan"]:::proxy
          C["工具计划控制点<br/>LLM plan + pre-tool gate"]:::gate
          D["工具输出控制点<br/>OpenClaw skill + post-tool gate"]:::provider
          E["Trace / Audit<br/>证据落盘"]:::audit
          N1["边界 1<br/>入口不可信"]:::block
          N2["边界 2<br/>工具计划不可信"]:::block
          N3["边界 3<br/>工具结果不可信"]:::block
          L["控制原则<br/>三类跨边界数据均先检查再进入下一阶段"]:::note

          A --> B --> C --> D --> E
          N1 -.-> B
          N2 -.-> C
          N3 -.-> D
          L -.-> B
          L -.-> C
          L -.-> D
    """)),
    FlowFigure("fig_3_1_architecture", 2300, 1300, chart("""
        flowchart LR
          subgraph I["入口层"]
            T["Telegram Bridge<br/>外部消息适配"]:::ingress
            O["其他入口<br/>统一调用 /agent/chat"]:::ingress
          end
          subgraph R["Agent Runtime :8002"]
            R1["运行图<br/>会话 / 角色 / 策略"]:::runtime
            R2["LLM 调用<br/>DeepSeek"]:::llm
            R3["pre / post gate<br/>工具前后门控"]:::gate
          end
          subgraph C["工具生态"]
            C1["OpenClaw skills / hooks"]:::provider
            C2["MCP provider slot<br/>扩展边界"]:::provider
          end
          subgraph P["Proxy Service :8000"]
            P1["/v1/scan<br/>scan-only 输入扫描"]:::proxy
            P2["Control Plane<br/>runtime spec"]:::proxy
            P3["/v1/interventions<br/>审批队列"]:::proxy
          end
          subgraph F["Frontend :3000 本地控制台"]
            F1["Attack / Compare"]:::runtime
            F2["Approvals / Audit"]:::runtime
            F3["Trace / Settings"]:::runtime
          end
          S1["SQLite + Memory<br/>Trace / Audit / Intervention"]:::audit

          T --> R1
          O --> R1
          R1 --> P1 --> R2 --> R3
          R3 --> C1 --> R3
          R3 -.未来扩展.-> C2
          P2 --> R1
          P3 --> R3
          F --> P
          F --> R
          R1 --> S1
          P1 --> S1
    """)),
    FlowFigure("fig_4_1_method_overview", 2100, 1200, chart("""
        flowchart LR
          subgraph A1["模型调用前"]
            U["用户消息"]:::ingress
            N["输入解析<br/>会话加载"]:::runtime
            S["Proxy /v1/scan<br/>风险判断"]:::proxy
            U --> N --> S
          end
          subgraph A2["工具执行前"]
            L["LLM 回复<br/>或工具计划"]:::llm
            P["pre-tool gate<br/>RBAC / Schema / 限额"]:::gate
            L --> P
          end
          subgraph A3["工具执行后"]
            X["Provider<br/>OpenClaw / MCP slot"]:::provider
            Q["post-tool gate<br/>PII / Secrets / 注入"]:::gate
            R["最终回复"]:::audit
            X --> Q --> R
          end
          IB["input_block<br/>模型前阻断"]:::block
          TC["tool_block / confirmation<br/>真实工具前暂停"]:::block
          OB["output_block / redact / truncate<br/>结果进入上下文前处理"]:::modify
          TR["Trace / Audit<br/>记录输入、计划、门控、执行、清洗"]:::note

          S -->|ALLOW / MODIFY| L
          P -->|ALLOW| X
          S -->|BLOCK| IB --> TR
          P -->|BLOCK / CONFIRM| TC --> TR
          Q -->|BLOCK / REDACT / TRUNCATE| OB --> R
          S -.-> TR
          P -.-> TR
          X -.-> TR
          Q -.-> TR
    """)),
    FlowFigure("fig_4_2_scan_pipeline", 2200, 1050, chart("""
        flowchart LR
          A["parse_node<br/>消息规范化"]:::runtime
          B["intent_node<br/>意图分类"]:::runtime
          C["rules_node<br/>denylist / 编码 / 长度"]:::proxy
          D["parallel_scanners_node<br/>LLM Guard / NeMo"]:::llm
          E["decision_node<br/>风险聚合"]:::gate
          F["request audit<br/>请求审计"]:::audit
          X["request-local<br/>denylist_hits 共享状态"]:::note
          G["ALLOW<br/>HTTP 200"]:::allow
          H["MODIFY<br/>HTTP 200"]:::modify
          I["BLOCK<br/>HTTP 403"]:::block

          A --> B --> C --> D --> E --> F
          C -.共享命中.-> X
          B -.复用命中.-> X
          E --> G
          E --> H
          E --> I
    """)),
    FlowFigure("fig_4_3_risk_decision", 2100, 1150, chart("""
        flowchart LR
          subgraph S["风险信号"]
            A["Intent<br/>越权 / 泄露 / 注入"]:::runtime
            B["Rules<br/>denylist / 编码 / 长度"]:::proxy
            C["Scanners<br/>LLM Guard / NeMo"]:::llm
            D["PII / Secrets<br/>敏感实体"]:::gate
            E["score_boost<br/>自定义风险提升"]:::audit
          end
          F["风险聚合<br/>risk_score 0-1"]:::gate
          G{"决策规则"}:::gate
          H["BLOCK<br/>denylist 或 risk >= max_risk"]:::block
          I["MODIFY<br/>PII mask / 参数清洗"]:::modify
          J["ALLOW<br/>无高风险信号"]:::allow
          K["解释字段<br/>flags / reason / intent"]:::note

          A --> F
          B --> F
          C --> F
          D --> F
          E --> F
          F --> G
          G --> H
          G --> I
          G --> J
          F --> K
    """)),
    FlowFigure("fig_4_4_agent_runtime_graph", 2200, 1250, chart("""
        flowchart LR
          subgraph B1["上下文与策略解析"]
            A["input_node<br/>用户消息"]:::ingress
            B["load_context<br/>历史与 runtime spec"]:::runtime
            C["resolve_role<br/>未知显式角色 fail-closed"]:::gate
            D["policy_node<br/>策略与工具 allowlist"]:::proxy
            A --> B --> C --> D
          end
          subgraph B2["模型调用与工具循环"]
            E["llm_call_node<br/>模型调用前 /v1/scan"]:::llm
            F{"工具计划?"}:::gate
            G["pre_tool_gate_node<br/>执行前检查"]:::gate
            H["tool_executor_node<br/>OpenClaw provider"]:::provider
            I["post_tool_gate_node<br/>结果清洗"]:::gate
            E --> F
            F -->|有工具| G --> H --> I
            I --> E
          end
          subgraph B3["回复与证据"]
            J["response_node<br/>最终回复"]:::audit
            K["memory_node<br/>会话记忆"]:::audit
            T["TraceAccumulator<br/>全链路证据"]:::note
            M["max_iterations = 3<br/>避免循环调用"]:::note
            J --> K
          end

          D --> E
          F -->|无工具| J
          G -->|BLOCK / CONFIRM| J
          E -->|输入 BLOCK| J
          B -.-> T
          E -.-> T
          G -.-> T
          H -.-> T
          I -.-> T
          M -.约束.-> F
    """)),
    FlowFigure("fig_4_5_pre_tool_gate", 2000, 1150, chart("""
        flowchart LR
          A["模型工具计划<br/>tool name + args"]:::llm
          B["执行前检查集合<br/>RBAC / Schema / Context risk<br/>Limits / Confirmation"]:::gate
          C{"pre-tool decision"}:::gate
          D["ALLOW<br/>直接执行"]:::allow
          E["MODIFY<br/>清洗参数后执行"]:::modify
          F["BLOCK<br/>真实工具不执行"]:::block
          G["REQUIRE_CONFIRMATION<br/>进入审批队列"]:::block

          A --> B --> C
          C --> D
          C --> E
          C --> F
          C --> G
    """)),
    FlowFigure("fig_4_6_post_tool_gate", 2000, 1150, chart("""
        flowchart LR
          A["工具原始输出<br/>不可信"]:::provider
          B["输出检查集合<br/>Injection / PII / Secrets / Size"]:::gate
          C{"post-tool decision"}:::gate
          D["PASS<br/>进入上下文"]:::allow
          E["REDACT<br/>脱敏后进入上下文"]:::modify
          F["TRUNCATE<br/>截断后进入上下文"]:::modify
          G["BLOCK<br/>占位符替代原结果"]:::block

          A --> B --> C
          C --> D
          C --> E
          C --> F
          C --> G
    """)),
    FlowFigure("fig_4_7_openclaw_bridge", 2100, 1200, chart("""
        flowchart LR
          A["runtime spec<br/>provider_type=openclaw"]:::runtime
          B["tool_protection<br/>gate flag 优先级"]:::gate
          C["build_scoped_prompt<br/>限定 skill 与参数"]:::proxy
          D["OpenClaw CLI/runtime<br/>openclaw agent ..."]:::provider
          E["CLI 输出解析<br/>JSON / envelope / logs"]:::llm
          F["provider result<br/>stdout / structured data"]:::provider
          G["post-tool gate<br/>清洗后回流"]:::gate
          H["session 派生<br/>agent-firewall-&lt;hash&gt;"]:::note
          I["异常处理<br/>timeout / stderr / HTTP 502"]:::block

          A --> B --> C --> D --> E --> F --> G
          H -.注入运行参数.-> D
          D -.失败.-> I
          E -.容忍插件日志和包络.-> F
    """)),
    FlowFigure("fig_4_8_intervention_state", 2000, 1050, chart("""
        flowchart LR
          A["触发暂停<br/>input_block / tool_block / confirmation"]:::block
          B["pending<br/>等待人工审批"]:::modify
          C["approved<br/>允许重放"]:::allow
          D["completed<br/>执行完成"]:::audit
          E["rejected<br/>不重放"]:::block
          F["failed<br/>执行失败"]:::block
          G["approved_intervention_id<br/>重放时复核"]:::note

          A --> B
          B -->|批准| C --> G --> D
          B -->|拒绝| E
          C -->|执行异常| F
    """)),
    FlowFigure("fig_4_9_trace_evidence", 2100, 1200, chart("""
        flowchart LR
          A["请求元数据<br/>session / role / policy / model"]:::runtime
          B["输入扫描证据<br/>intent / risk / decision"]:::proxy
          C["工具计划与 pre-tool<br/>tool / args / checks"]:::gate
          D["工具执行与 post-tool<br/>provider / latency / sanitization"]:::provider
          E["最终回复<br/>errors / counters"]:::audit
          F["Trace-run<br/>可复核证据链"]:::note
          G["审计回答<br/>哪层拦截 / 是否执行 / 结果是否进入上下文"]:::note

          A --> B --> C --> D --> E
          B -.-> F
          C -.-> F
          D -.-> F
          E -.-> F --> G
    """)),
]


class CdpClient:
    def __init__(self, ws_url: str) -> None:
        self.ws = websocket.create_connection(ws_url, timeout=10)
        self.counter = 0

    def call(self, method: str, params: dict | None = None) -> dict:
        self.counter += 1
        payload = {"id": self.counter, "method": method}
        if params:
            payload["params"] = params
        self.ws.send(json.dumps(payload))
        while True:
            message = json.loads(self.ws.recv())
            if message.get("id") == self.counter:
                if "error" in message:
                    raise RuntimeError(message["error"])
                return message.get("result", {})

    def close(self) -> None:
        self.ws.close()


def free_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.bind(("127.0.0.1", 0))
        return int(sock.getsockname()[1])


def html_for(code: str, target_width: int) -> str:
    escaped = code.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")
    return f"""<!doctype html>
<html>
<head>
  <meta charset=\"utf-8\">
  <style>
    html, body {{ margin: 0; padding: 0; background: #ffffff; }}
    body {{ font-family: \"Arial Unicode MS\", \"PingFang SC\", \"Helvetica Neue\", Arial, sans-serif; }}
    #diagram {{ padding: 48px; display: inline-block; background: #ffffff; }}
    svg {{ max-width: none !important; height: auto !important; }}
  </style>
</head>
<body>
  <div id=\"diagram\">Rendering...</div>
  <script type=\"module\">
    import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';
    mermaid.initialize({{
      startOnLoad: false,
      securityLevel: 'loose',
      theme: 'base',
      flowchart: {{ htmlLabels: true, curve: 'basis', nodeSpacing: 75, rankSpacing: 88, padding: 20 }},
      themeVariables: {{
        background: '#ffffff',
        mainBkg: '#eff6ff',
        primaryColor: '#dbeafe',
        primaryBorderColor: '#2563eb',
        primaryTextColor: '#111827',
        lineColor: '#475569',
        textColor: '#111827',
        fontFamily: 'Arial Unicode MS, PingFang SC, Helvetica Neue, Arial, sans-serif',
        fontSize: '22px',
        edgeLabelBackground: '#ffffff',
        clusterBkg: '#f8fafc',
        clusterBorder: '#94a3b8'
      }}
    }});
    const rendered = await mermaid.render('generatedDiagram', `{escaped}`);
    document.getElementById('diagram').innerHTML = rendered.svg;
    const svg = document.querySelector('svg');
    if (svg) {{
      svg.removeAttribute('height');
      const targetWidth = Math.min({target_width}, window.innerWidth - 96);
      svg.style.width = targetWidth + 'px';
      svg.style.height = 'auto';
      svg.style.display = 'block';
    }}
    document.body.dataset.ready = 'true';
  </script>
</body>
</html>
"""


def crop_png(path: Path) -> None:
    img = Image.open(path).convert("RGB")
    bg = Image.new("RGB", img.size, "white")
    bbox = ImageChops.difference(img, bg).getbbox()
    if bbox is None:
        raise RuntimeError(f"blank render: {path}")
    margin = 72
    crop = img.crop((
        max(0, bbox[0] - margin),
        max(0, bbox[1] - margin),
        min(img.width, bbox[2] + margin),
        min(img.height, bbox[3] + margin),
    ))
    if crop.width < 800 or crop.height < 350:
        raise RuntimeError(f"unexpected small render: {path} {crop.size}")
    crop.save(path, optimize=True)


def render(fig: FlowFigure) -> None:
    SOURCE_DIR.mkdir(parents=True, exist_ok=True)
    TMP_DIR.mkdir(parents=True, exist_ok=True)
    (SOURCE_DIR / f"{fig.slug}.mmd").write_text(fig.code, encoding="utf-8")
    html = TMP_DIR / f"{fig.slug}.html"
    html.write_text(html_for(fig.code, max(1200, fig.width - 180)), encoding="utf-8")
    output = IMAGE_DIR / f"{fig.slug}.png"
    output.unlink(missing_ok=True)
    profile = TMP_DIR / f"profile-{fig.slug}"
    subprocess.run(["/bin/rm", "-rf", str(profile)], check=False)
    port = free_port()
    cmd = [
        str(CHROME), "--headless=new", "--disable-gpu",
        "--disable-background-networking", "--disable-component-update",
        "--disable-sync", "--disable-default-apps", "--disable-extensions",
        "--no-first-run", "--no-default-browser-check", "--hide-scrollbars",
        "--remote-allow-origins=*", f"--remote-debugging-port={port}",
        f"--window-size={fig.width},{fig.height}", f"--user-data-dir={profile}",
        html.as_uri(),
    ]
    log = TMP_DIR / f"{fig.slug}.log"
    with log.open("w", encoding="utf-8") as fh:
        proc = subprocess.Popen(cmd, stdout=fh, stderr=fh)
    client: CdpClient | None = None
    try:
        targets = None
        for _ in range(40):
            try:
                with urllib.request.urlopen(f"http://127.0.0.1:{port}/json", timeout=1) as response:
                    targets = json.loads(response.read().decode("utf-8"))
                if targets:
                    break
            except Exception:
                time.sleep(0.25)
        if not targets:
            raise RuntimeError(f"failed to connect to Chrome for {fig.slug}; see {log}")
        target = next((item for item in targets if item.get("type") == "page"), targets[0])
        client = CdpClient(target["webSocketDebuggerUrl"])
        client.call("Page.enable")
        client.call("Runtime.enable")
        ready = False
        for _ in range(80):
            result = client.call(
                "Runtime.evaluate",
                {
                    "expression": "document.body.dataset.ready === 'true'",
                    "returnByValue": True,
                },
            )
            if result.get("result", {}).get("value") is True:
                ready = True
                break
            time.sleep(0.25)
        if not ready:
            raise RuntimeError(f"Mermaid did not finish rendering {fig.slug}; see {log}")
        client.call(
            "Runtime.evaluate",
            {
                "expression": "document.fonts.ready.then(() => true)",
                "awaitPromise": True,
                "returnByValue": True,
            },
        )
        metrics = client.call(
            "Runtime.evaluate",
            {
                "expression": """
                (() => {
                  const d = document.getElementById('diagram');
                  const r = d.getBoundingClientRect();
                  return {
                    x: Math.max(0, Math.floor(r.left)),
                    y: Math.max(0, Math.floor(r.top)),
                    width: Math.ceil(r.width),
                    height: Math.ceil(r.height)
                  };
                })()
                """,
                "returnByValue": True,
            },
        )["result"]["value"]
        if metrics["width"] < 800 or metrics["height"] < 300:
            raise RuntimeError(f"unexpected Mermaid dimensions {fig.slug}: {metrics}")
        screenshot = client.call(
            "Page.captureScreenshot",
            {
                "format": "png",
                "captureBeyondViewport": True,
                "fromSurface": True,
                "clip": {
                    "x": metrics["x"],
                    "y": metrics["y"],
                    "width": metrics["width"],
                    "height": metrics["height"],
                    "scale": 2,
                },
            },
        )
        output.write_bytes(base64.b64decode(screenshot["data"]))
        crop_png(output)
    finally:
        if client:
            client.close()
        subprocess.run(["/usr/bin/pkill", "-f", str(profile)], check=False)
        proc.kill()
        try:
            proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            proc.terminate()
        subprocess.run(["/bin/rm", "-rf", str(profile)], check=False)
    print(f"rendered {fig.slug}")


def main() -> None:
    if not CHROME.exists():
        raise SystemExit(f"Chrome not found: {CHROME}")
    for fig in FIGURES:
        render(fig)
    subprocess.run(["/bin/rm", "-rf", str(TMP_DIR)], check=False)


if __name__ == "__main__":
    main()
